### ISSUE TITLE
如果我不指定required，只指定mobile，难道不应该当值不为空时才验证吗？

### ISSUE THREAD

**Issue by jadestrong** [liuyinglong/verify#6]
我是想手机号不是必填，但当输入了手机号时也必须是符合规则的，可在提交时提示手机号格式不对啊

**Comment by liuyinglong** [comment]
您好 这里我理解的逻辑是为空的时候也不符合手机号码验证规则，所以为空的时候也做了验证。
根据您的需求，您可以自定义验证规则。
