### ISSUE TITLE
在run build时报错了

### ISSUE THREAD

**Issue by yellowSTA** [liuyinglong/verify#7]
ERROR in static/js/1.d0154e062764d39fded8.js from UglifyJs
Unexpected token name «i», expected punc «;» [./~/vue-verify-plugin/src/verify.js:196,0][static/js/1.d0154e062764d39fded8.js:21118,21]

不知道这是个怎么回事

**Comment by liuyinglong** [comment]
您好，在我这里没有重现，您重新安装一下依赖再试一下呢？

**Comment by yellowSTA** [comment]
在verify.js大概196行的位置，在一个for循环中使用了一个es6的let，不知道是babel没有配置好还是别的原因，导致运行时错误；将let改为var就能正常运行

**Comment by liuyinglong** [comment]
此问题已解决 谢谢您
